version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123Momia
      MYSQL_DATABASE: mautic
      MYSQL_USER: maut
      MYSQL_PASSWORD: 123Momia
  mautic:
    depends_on:
      - db
    image: mautic/mautic:v4-apache
    ports:
      - "5656:80"
    restart: always
    environment:
      MAUTIC_DB_HOST: db:3306
      MAUTIC_DB_USER: maut
      MAUTIC_DB_PASSWORD: 123Momia
      MAUTIC_DB_NAME: mautic
      MAUTIC_VERSION: '4'
volumes:
  db_data: